Repository seoul-milk-team3/seoulmilk-backend, pull requests merged in 2025-03, with the labels that each got.

#13 Feat: (#4) 회원가입 및 로그인 구현
  build.gradle
  src/main/java/com/seoulmilk/be/auth/dto/request/LoginRequest.java
  src/main/java/com/seoulmilk/be/auth/dto/request/SignUpRequest.java
  src/main/java/com/seoulmilk/be/auth/exception/ExistUserException.java
  src/main/java/com/seoulmilk/be/auth/exception/errorCode/AuthErrorCode.java
  src/main/java/com/seoulmilk/be/auth/presentation/AuthController.java
  src/main/java/com/seoulmilk/be/auth/presentation/api/AuthApi.java
  src/main/java/com/seoulmilk/be/auth/service/AuthService.java
  src/main/java/com/seoulmilk/be/global/config/SecurityConfig.java
  src/main/java/com/seoulmilk/be/global/config/SwaggerConfig.java
  src/main/java/com/seoulmilk/be/global/dto/SuccessCode.java
  src/main/java/com/seoulmilk/be/global/dto/SuccessResponse.java
  src/main/java/com/seoulmilk/be/global/exception/errorcode/GlobalErrorCode.java
  src/main/java/com/seoulmilk/be/global/exception/errorcode/UserNotFoundException.java
  src/main/java/com/seoulmilk/be/global/jwt/application/JwtService.java
  src/main/java/com/seoulmilk/be/global/jwt/dto/response/TokenResponse.java
  src/main/java/com/seoulmilk/be/global/jwt/exception/InvalidTokenException.java
  src/main/java/com/seoulmilk/be/global/jwt/exception/JwtErrorCode.java
  src/main/java/com/seoulmilk/be/global/jwt/exception/TokenCreateException.java
  src/main/java/com/seoulmilk/be/global/jwt/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/seoulmilk/be/global/jwt/refresh/application/RefreshTokenService.java
  src/main/java/com/seoulmilk/be/global/jwt/refresh/domain/RefreshToken.java
  src/main/java/com/seoulmilk/be/global/jwt/refresh/exception/RefreshErrorCode.java
  src/main/java/com/seoulmilk/be/global/jwt/refresh/exception/RefreshTokenNotFoundException.java
  src/main/java/com/seoulmilk/be/global/jwt/refresh/persistence/RefreshTokenRepository.java
  src/main/java/com/seoulmilk/be/global/security/CustomUserDetails.java
  src/main/java/com/seoulmilk/be/global/security/CustomUserDetailsService.java
  src/main/java/com/seoulmilk/be/tax/domain/type/AmendCode.java
  src/main/java/com/seoulmilk/be/tax/domain/type/IpTypeCode.java
  src/main/java/com/seoulmilk/be/tax/domain/type/TypeCode.java
  src/main/java/com/seoulmilk/be/user/domain/type/Role.java
  src/main/java/com/seoulmilk/be/user/exception/UserNotFoundException.java
  src/main/java/com/seoulmilk/be/user/exception/errorCode/UserErrorCode.java
  src/main/java/com/seoulmilk/be/user/persistence/UserRepository.java
  src/main/java/com/seoulmilk/be/user/presentation/UserController.java
  src/main/java/com/seoulmilk/be/user/presentation/api/UserApi.java
Labels: ✨ feat

#17 Feat(#12): OCR 처리 기능
  build.gradle
  src/main/java/com/seoulmilk/be/auth/presentation/api/AuthApi.java
  src/main/java/com/seoulmilk/be/auth/service/AuthService.java
  src/main/java/com/seoulmilk/be/global/application/SimpleStorageService.java
  src/main/java/com/seoulmilk/be/global/config/ConfigurationPropsConfig.java
  src/main/java/com/seoulmilk/be/global/config/OpenFeignConfig.java
  src/main/java/com/seoulmilk/be/global/config/SecurityConfig.java
  src/main/java/com/seoulmilk/be/global/config/SwaggerConfig.java
  src/main/java/com/seoulmilk/be/global/dto/SuccessCode.java
  src/main/java/com/seoulmilk/be/global/util/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/seoulmilk/be/tax/application/NtsTaxService.java
  src/main/java/com/seoulmilk/be/tax/application/ext/ClovaOcrClient.java
  src/main/java/com/seoulmilk/be/tax/application/ext/ClovaOcrProperties.java
  src/main/java/com/seoulmilk/be/tax/domain/NtsTax.java
  src/main/java/com/seoulmilk/be/tax/dto/request/ClovaOcrRequest.java
  src/main/java/com/seoulmilk/be/tax/dto/request/TaxInvoicesSaveRequest.java
  src/main/java/com/seoulmilk/be/tax/dto/request/TaxInvoicesSaveRequestList.java
  src/main/java/com/seoulmilk/be/tax/dto/response/ClovaOcrResponse.java
  src/main/java/com/seoulmilk/be/tax/persistence/NtsTaxRepository.java
  src/main/java/com/seoulmilk/be/tax/presentation/NtsTaxController.java
  src/main/java/com/seoulmilk/be/tax/presentation/api/NtxTaxApi.java
  src/main/java/com/seoulmilk/be/user/persistence/init/UserDummy.java
  src/test/java/com/seoulmilk/be/global/application/SimpleStorageServiceTest.java
Labels: ✨ feat, 🐛 fix

#19 Feat(#18) : 자료 조회
  src/main/java/com/seoulmilk/be/auth/presentation/api/AuthApi.java
  src/main/java/com/seoulmilk/be/global/dto/SuccessCode.java
  src/main/java/com/seoulmilk/be/tax/application/NtsTaxService.java
  src/main/java/com/seoulmilk/be/tax/domain/NtsTax.java
  src/main/java/com/seoulmilk/be/tax/domain/type/ResultType.java
  src/main/java/com/seoulmilk/be/tax/dto/response/OfficeTaxFilterResponse.java
  src/main/java/com/seoulmilk/be/tax/persistence/NtsTaxRepository.java
  src/main/java/com/seoulmilk/be/tax/persistence/NtsTaxRepositoryCustom.java
  src/main/java/com/seoulmilk/be/tax/persistence/NtsTaxRepositoryCustomImpl.java
  src/main/java/com/seoulmilk/be/tax/persistence/init/NtsTaxDummy.java
  src/main/java/com/seoulmilk/be/tax/presentation/NtsTaxController.java
  src/main/java/com/seoulmilk/be/tax/presentation/api/NtxTaxApi.java
Labels: ✨ feat

#20 Feat(#14) 세금계산서 진위여부 검증 기능 구현
  build.gradle
  src/main/java/com/seoulmilk/be/BeApplication.java
  src/main/java/com/seoulmilk/be/auth/dto/request/BranchSignUpRequest.java
  src/main/java/com/seoulmilk/be/auth/dto/request/OfficeSignUpRequest.java
  src/main/java/com/seoulmilk/be/auth/exception/errorcode/AuthErrorCode.java
  src/main/java/com/seoulmilk/be/auth/presentation/AuthController.java
  src/main/java/com/seoulmilk/be/auth/presentation/api/AuthApi.java
  src/main/java/com/seoulmilk/be/auth/service/AuthService.java
  src/main/java/com/seoulmilk/be/global/config/RedisConfig.java
  src/main/java/com/seoulmilk/be/global/dto/SuccessCode.java
  src/main/java/com/seoulmilk/be/tax/domain/NtsTax.java
  src/main/java/com/seoulmilk/be/tax/domain/type/ResultType.java
  src/main/java/com/seoulmilk/be/tax/exception/NtsTaxNotFoundException.java
  src/main/java/com/seoulmilk/be/tax/exception/errorcode/NtsTaxErrorCode.java
  src/main/java/com/seoulmilk/be/taxvalidation/application/CodefApiCacheService.java
  src/main/java/com/seoulmilk/be/taxvalidation/application/TaxValidationService.java
  src/main/java/com/seoulmilk/be/taxvalidation/dto/request/CodefRequest.java
  src/main/java/com/seoulmilk/be/taxvalidation/dto/response/InvoiceVerificationResponse.java
  src/main/java/com/seoulmilk/be/taxvalidation/exception/TaxValidationException.java
  src/main/java/com/seoulmilk/be/taxvalidation/exception/errorcode/TaxValidationErrorCode.java
  src/main/java/com/seoulmilk/be/taxvalidation/infrastructure/auth/EasyCodefProvider.java
  src/main/java/com/seoulmilk/be/taxvalidation/infrastructure/constants/CodefParameter.java
  src/main/java/com/seoulmilk/be/taxvalidation/infrastructure/constants/CodefResponseCode.java
  src/main/java/com/seoulmilk/be/taxvalidation/infrastructure/request/EasyCodefRequestFactory.java
  src/main/java/com/seoulmilk/be/taxvalidation/presentation/TaxValidationController.java
  src/main/java/com/seoulmilk/be/taxvalidation/presentation/api/TaxValidationApi.java
  src/main/java/com/seoulmilk/be/user/domain/User.java
  src/main/java/com/seoulmilk/be/user/domain/type/Telecom.java
Labels: ✨ feat

#23 Feat(#22) 대리점 회원가입 필요 정보 변경
  src/main/java/com/seoulmilk/be/auth/dto/request/BranchSignUpRequest.java
  src/main/java/com/seoulmilk/be/auth/dto/request/OfficeSignUpRequest.java
  src/main/java/com/seoulmilk/be/user/domain/User.java
Labels: ✨ feat

#26 Feat: (#25) Codef API 요청할 때 '-' 제거
  src/main/java/com/seoulmilk/be/auth/exception/errorcode/AuthErrorCode.java
  src/main/java/com/seoulmilk/be/auth/presentation/api/AuthApi.java
  src/main/java/com/seoulmilk/be/taxvalidation/application/TaxValidationService.java
  src/main/java/com/seoulmilk/be/taxvalidation/infrastructure/codef/EasyCodefProvider.java
  src/main/java/com/seoulmilk/be/taxvalidation/infrastructure/request/EasyCodefRequestFactory.java
Labels: ✨ feat

#27 Feat: (#18) 진위 여부 확인 전 자료 조회와 상세 조회
  src/main/java/com/seoulmilk/be/global/config/SwaggerConfig.java
  src/main/java/com/seoulmilk/be/global/domain/BaseTimeEntity.java
  src/main/java/com/seoulmilk/be/global/dto/SuccessCode.java
  src/main/java/com/seoulmilk/be/global/presentation/api/globalApi.java
  src/main/java/com/seoulmilk/be/tax/application/NtsTaxService.java
  src/main/java/com/seoulmilk/be/tax/application/OfficeTaxService.java
  src/main/java/com/seoulmilk/be/tax/domain/NtsTax.java
  src/main/java/com/seoulmilk/be/tax/dto/request/TaxInvoicesSaveRequest.java
  src/main/java/com/seoulmilk/be/tax/dto/response/BeforeValidateTaxResponse.java
  src/main/java/com/seoulmilk/be/tax/dto/response/OfficeTaxDetailResponse.java
  src/main/java/com/seoulmilk/be/tax/dto/response/OfficeTaxFilterResponse.java
  src/main/java/com/seoulmilk/be/tax/persistence/NtsTaxRepository.java
  src/main/java/com/seoulmilk/be/tax/persistence/NtsTaxRepositoryCustom.java
  src/main/java/com/seoulmilk/be/tax/persistence/NtsTaxRepositoryCustomImpl.java
  src/main/java/com/seoulmilk/be/tax/persistence/init/NtsTaxDummy.java
  src/main/java/com/seoulmilk/be/tax/presentation/NtsTaxController.java
  src/main/java/com/seoulmilk/be/tax/presentation/OfficeTaxController.java
  src/main/java/com/seoulmilk/be/tax/presentation/api/NtxTaxApi.java
  src/main/java/com/seoulmilk/be/tax/presentation/api/OfficeTaxApi.java
  src/main/java/com/seoulmilk/be/taxvalidation/application/TaxValidationService.java
Labels: ✨ feat

#34 Fix: (#33) CORS 관련 오류 해결
  src/main/java/com/seoulmilk/be/global/config/CorsConfig.java
Labels: 🐛 fix

#38 Feat: (#36) 세금계산서 검증 다건 요청 구현
  build.gradle
  src/main/java/com/seoulmilk/be/tax/application/NtsTaxService.java
  src/main/java/com/seoulmilk/be/taxvalidation/application/CodefCacheService.java
  src/main/java/com/seoulmilk/be/taxvalidation/application/TaxValidationService.java
  src/main/java/com/seoulmilk/be/taxvalidation/application/thread/CodefRequestThread.java
  src/main/java/com/seoulmilk/be/taxvalidation/application/thread/CodefRequestThreadManager.java
  src/main/java/com/seoulmilk/be/taxvalidation/dto/request/CodefRequest.java
  src/main/java/com/seoulmilk/be/taxvalidation/dto/request/InvoiceValidationRequest.java
  src/main/java/com/seoulmilk/be/taxvalidation/dto/response/InvoiceVerificationResponse.java
  src/main/java/com/seoulmilk/be/taxvalidation/exception/errorcode/TaxValidationErrorCode.java
  src/main/java/com/seoulmilk/be/taxvalidation/infrastructure/constants/CodefParameter.java
  src/main/java/com/seoulmilk/be/taxvalidation/infrastructure/constants/CodefResponseCode.java
  src/main/java/com/seoulmilk/be/taxvalidation/infrastructure/request/EasyCodefRequestFactory.java
  src/main/java/com/seoulmilk/be/taxvalidation/presentation/TaxValidationController.java
  src/main/java/com/seoulmilk/be/taxvalidation/presentation/api/TaxValidationApi.java
Labels: ✨ feat

#39 Feat: (#32) OCR 관련 기능 수정
  src/main/java/com/seoulmilk/be/auth/service/AuthService.java
  src/main/java/com/seoulmilk/be/global/config/CorsConfig.java
  src/main/java/com/seoulmilk/be/global/dto/SuccessCode.java
  src/main/java/com/seoulmilk/be/tax/application/NtsTaxService.java
  src/main/java/com/seoulmilk/be/tax/application/OfficeTaxService.java
  src/main/java/com/seoulmilk/be/tax/domain/NtsTax.java
  src/main/java/com/seoulmilk/be/tax/domain/type/RegionType.java
  src/main/java/com/seoulmilk/be/tax/domain/type/ResultType.java
  src/main/java/com/seoulmilk/be/tax/dto/request/BranchTaxFilterRequest.java
  src/main/java/com/seoulmilk/be/tax/dto/request/TaxInvoicesSaveRequest.java
  src/main/java/com/seoulmilk/be/tax/dto/request/TaxInvoicesSaveRequestList.java
  src/main/java/com/seoulmilk/be/tax/dto/response/BeforeValidateTaxResponseList.java
  src/main/java/com/seoulmilk/be/tax/dto/response/ClovaOcrResponse.java
  src/main/java/com/seoulmilk/be/tax/dto/response/OfficeTaxDetailResponse.java
  src/main/java/com/seoulmilk/be/tax/dto/response/OfficeValidateAbnormalTaxResponse.java
  src/main/java/com/seoulmilk/be/tax/dto/response/OfficeValidateAbnormalTaxResponseList.java
  src/main/java/com/seoulmilk/be/tax/persistence/NtsTaxRepositoryCustom.java
  src/main/java/com/seoulmilk/be/tax/persistence/NtsTaxRepositoryCustomImpl.java
  src/main/java/com/seoulmilk/be/tax/persistence/init/NtsTaxDummy.java
  src/main/java/com/seoulmilk/be/tax/presentation/NtsTaxController.java
  src/main/java/com/seoulmilk/be/tax/presentation/OfficeTaxController.java
  src/main/java/com/seoulmilk/be/tax/presentation/api/NtxTaxApi.java
  src/main/java/com/seoulmilk/be/tax/presentation/api/OfficeTaxApi.java
  src/main/java/com/seoulmilk/be/taxvalidation/application/TaxValidationService.java
  src/main/java/com/seoulmilk/be/taxvalidation/application/thread/CodefRequestThread.java
  src/main/java/com/seoulmilk/be/taxvalidation/dto/response/InvoiceVerificationResponse.java
Labels: ✨ feat

#45 Feat (#44) 세금계산서 검증 여부 갱신
  src/main/java/com/seoulmilk/be/taxvalidation/application/TaxValidationService.java
  src/main/java/com/seoulmilk/be/taxvalidation/presentation/TaxValidationController.java
Labels: ✨ feat

#46 Feat: (#43) 조회 DTO 추가
  src/main/java/com/seoulmilk/be/tax/application/NtsTaxFacadeService.java
  src/main/java/com/seoulmilk/be/tax/application/NtsTaxService.java
  src/main/java/com/seoulmilk/be/tax/application/OfficeTaxService.java
  src/main/java/com/seoulmilk/be/tax/dto/response/OfficeTaxDetailResponse.java
  src/main/java/com/seoulmilk/be/tax/presentation/NtsTaxController.java
Labels: ✨ feat

#51 Fix: (#50) 대리점 필터링 조회 안되는 문제 해결
  src/main/java/com/seoulmilk/be/tax/application/BranchTaxService.java
  src/main/java/com/seoulmilk/be/tax/dto/request/BranchTaxFilterRequest.java
  src/main/java/com/seoulmilk/be/tax/persistence/NtsTaxRepositoryCustom.java
  src/main/java/com/seoulmilk/be/tax/persistence/NtsTaxRepositoryCustomImpl.java
  src/main/java/com/seoulmilk/be/tax/presentation/BranchTaxController.java
  src/main/java/com/seoulmilk/be/tax/presentation/api/BranchTaxApi.java
Labels: 🐛 fix

#53 Refactor: (#52) 세금계산서 검증 대기 시간 변경
  src/main/java/com/seoulmilk/be/taxvalidation/application/TaxValidationService.java
  src/main/java/com/seoulmilk/be/taxvalidation/application/thread/CodefRequestThread.java
Labels: ♻️ refactor
